# Generated by Django 2.2.19 on 2022-01-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_auto_20211228_1403"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-pub_date",),
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
