# Generated by Django 2.2.19 on 2022-01-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_auto_20220125_1053"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
    ]
