# Generated by Django 2.2.16 on 2022-02-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_auto_20220125_2213"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-pub_date", "id"),
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
